src/hortum/complaint/urls.py
from ..routers import OptionalSlashRouter
from . import viewsets

router = OptionalSlashRouter()
router.register(r'create', viewsets.ComplaintRegistrationAPIView, basename='createComplaint')
router.register(r'delete', viewsets.ComplaintDeleteAPIView, basename='deleteComplaint')
router.register(r'list(:?/(?P<emailProductor>.+))?', viewsets.ComplaintListAPIView, basename='listComplaint')

urlpatterns = [
] + router.urls

src/hortum/customer/urls.py
from rest_framework.routers import SimpleRouter

from ..routers import CustomUpdateRouter, OptionalSlashRouter
from . import viewsets

routerRegister = SimpleRouter()
routerRegister.register(r'', viewsets.CustomerRegistrationAPIView, basename='customer')

router = CustomUpdateRouter()
router.register(r'fav-announcement', viewsets.FavoritesAnnouncementsAPIView, basename='favAnnouncement')
router.register(r'fav-productor', viewsets.FavoriteProductorsAPIView, basename='favProductor')

listRouter = OptionalSlashRouter()
listRouter.register(r'favorites', viewsets.CustomerListFavoritesAPIView, basename='listFavAnnouncements')

urlpatterns = [
] + router.urls + listRouter.urls

src/hortum/urls.py
from .users import viewsets
from .users.urls import signup_urls
from .users.forms import CustomPasswordForm

from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static

from rest_framework import permissions
from rest_framework_simplejwt.views import TokenRefreshView

from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
   openapi.Info(
      title="Hortum API",
      default_version='v0.5.5',
      description="API do aplicativo Hortum",
      terms_of_service="https://fga-eps-mds.github.io/2020.2-Hortum/CONTRIBUTING/",
      contact=openapi.Contact(email="mdsgrupo6@gmail.com"),
      license=openapi.License(name="GPLv3 License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('login/', viewsets.CustomTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('login/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/test_token/', viewsets.is_token_valid, name='is_token_valid'),
    path('admin/', admin.site.urls),
    path('signup/', include(signup_urls)),
    path('announcement/', include('hortum.announcement.urls')),
    path('productor/', include('hortum.productor.urls')),
    path('customer/', include('hortum.customer.urls')),
    path('users/', include('hortum.users.urls')),
    path('complaint/', include('hortum.complaint.urls')),

    path('reset_password/', auth_views.PasswordResetView.as_view(
       template_name="hortum/password_reset.html",
       html_email_template_name="hortum/email_template_name.htm",), name='reset_password'),

    path('reset_password_done/', auth_views.PasswordResetDoneView.as_view(
       template_name="hortum/password_reset_done.html"), name='password_reset_done'),

    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(
       template_name="hortum/password_reset_confirm.html",
       form_class=CustomPasswordForm), name='password_reset_confirm'),

    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(
      template_name="hortum/password_reset_complete.html"), name='password_reset_complete'),
      
    url(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    url(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    url(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/hortum/users/urls.py
from django.urls import path, include

from ..productor.urls import routerRegister as productorRegister
from ..customer.urls import routerRegister as customerRegister
from ..routers import CustomUpdateRouter, CustomDeleteRouter, OptionalSlashRouter
from . import viewsets

router = CustomUpdateRouter()
router.register(r'change-password', viewsets.ChangePasswordView, basename='changePasswordUser')
router.register(r'update', viewsets.UpdateUserView, basename='updateUser')

customRouter = CustomDeleteRouter()
customRouter.register(r'delete', viewsets.UserDeleteAPIView, basename='deleteUser')

routerVerify = OptionalSlashRouter()
routerVerify.register(r'verify', viewsets.VerifyAccountView, basename='verifyEmail')

urlpatterns = router.urls + routerVerify.urls + customRouter.urls

signup_urls = [
    path('customer/', include(customerRegister.urls)),
    path('productor/', include(productorRegister.urls)),
]

src/hortum/announcement/models.py
from django.db import models

from ..productor.models import Productor


class Announcement(models.Model):

    TYPE_OF_PRODUCTS_CHOICES = [
        ('Artesanato', 'Artesanato'),
        ('Açúcar', 'Açúcar'),
        ('Bebidas', 'Bebidas'),
        ('Café', 'Café'),
        ('Carnes', 'Carnes'),
        ('Cogumelos', 'Cogumelos'),
        ('Derivados de trigo', 'Derivados de trigo'),
        ('Derivados de mandioca', 'Derivados de mandioca'),
        ('Derivados de cana', 'Derivados de cana'),
        ('Desidatrados', 'Desidratados'),
        ('Defumados', 'Defumados'),
        ('Doces', 'Doces'),
        ('Flores', 'Flores'),
        ('Frango Caipira', 'Frango Caipira'),
        ('Frutas', 'Frutas'),
        ('Graos', 'Graos'),
        ('Hortaliças', 'Hortaliças'),
        ('Laticinios', 'Laticinios'),
        ('Legumes', 'Legumes'),
        ('Ovos de Galinha', 'Ovos de Galinha'),
        ('Peixes', 'Peixes'),
        ('Polpa de frutas', 'Polpa de frutas'),
        ('Pratos congelados', 'Pratos congelados'),
        ('Sorvetes', 'Sorvetes'),
        ('Outros', 'Outros'),
    ]

    idProductor = models.ForeignKey(Productor, on_delete=models.CASCADE, related_name='announcements')
    likes = models.IntegerField(default=0)
    name = models.CharField(max_length=30)
    type_of_product = models.CharField(max_length=200, choices=TYPE_OF_PRODUCTS_CHOICES, default='Outros')
    description = models.CharField(max_length=200)
    price = models.FloatField(default=0.0)
    inventory = models.BooleanField(default=True)
    publicationDate = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-publicationDate']

class Localization(models.Model):
    idAnnoun = models.ForeignKey(Announcement, on_delete=models.CASCADE, related_name='localizations')
    adress = models.CharField(max_length=100)

class AnnouncementImage(models.Model):
    def upload_image_announ(instance, filename):
        return f"Announcement-{instance.idImage.name}-{filename}"

    idImage = models.ForeignKey(Announcement, on_delete=models.CASCADE, related_name='images')
    picture = models.ImageField(upload_to=upload_image_announ, null=True)

src/hortum/complaint/models.py
from django.db import models
from hortum.productor.models import Productor

class Complaint(models.Model):
    def upload_image(instance, filename):
        return f"Complaint-{instance.author}-{filename}"

    author = models.CharField(max_length=30)
    description = models.CharField(max_length=450)
    idProductor = models.ForeignKey(Productor, on_delete=models.CASCADE, related_name='reclamations')
    image = models.ImageField(upload_to=upload_image, null=True)
    emailCustomer = models.EmailField(max_length=100)

src/hortum/customer/models.py
from django.db import models
from hortum.productor.models import Productor
from hortum.announcement.models import Announcement
from hortum.users.models import User

class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    idAnunFav = models.ManyToManyField(Announcement)
    idProdFav = models.ManyToManyField(Productor)

src/hortum/productor/models.py
from django.db import models
from hortum.users.models import User

class Productor(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

src/hortum/reclamation/models.py
from django.db import models
from hortum.picture.models import Picture
from hortum.productor.models import Productor

class Reclamation(models.Model):
    author = models.CharField(max_length=100)
    description = models.CharField(max_length=450)
    idProductor = models.ForeignKey(Productor, on_delete=models.CASCADE, related_name='reclamations')
    idPicture = models.ForeignKey(Picture, on_delete=models.CASCADE, null=True)
    emailCustomer = models.EmailField(max_length=100)

src/hortum/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.mail import send_mail

from ..settings import EMAIL_HOST_USER as email_sender

from ..encode import encode_string

class User(AbstractUser):
    def upload_image(instance, filename):
        return f"Profile-{instance.username}-{filename}"

    username = models.CharField(max_length=30)
    email = models.EmailField(unique=True, max_length=120)
    phone_number = models.CharField(unique=True, blank=False, null=True, max_length=13)
    is_productor = models.BooleanField(default=False)
    profile_picture = models.ImageField(upload_to=upload_image, null=True, default="person-male.png")
    is_verified = models.BooleanField(default=False)

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def send_verification_email(request, email):
        encoded_email = encode_string(email)
        url_verify = ('https' if request.is_secure() else 'http') + '://' + request.get_host() + '/users/verify/' + encoded_email
        send_mail(
            'Hortum - verifique seu email',
			'Você está a um passo de acessar o Hortum, clique no link abaixo para concluir seu registro:\n' + url_verify,
			email_sender,
			[email],
			fail_silently=False,
		)

src/hortum/users/forms.py
from django.contrib.auth.forms import SetPasswordForm
from django.contrib.auth import password_validation
from django import forms


class CustomPasswordForm(SetPasswordForm):
    """
    Form para redefinição de senha
    """
    error_messages = {
        'password_mismatch': ("As senhas inseridas não são iguais"),
    }
    new_password1 = forms.CharField(
        label=("Nova senha"),
        widget=forms.PasswordInput,
        strip=False,
        help_text=password_validation.password_validators_help_text_html(),
    )

    new_password2 = forms.CharField(
        label=("Confirme nova senha"),
        widget=forms.PasswordInput,
        strip=False,
    )

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(SetPasswordForm, self).__init__(*args, **kwargs)

    def clean_new_password2(self):
        password1 = self.cleaned_data.get('new_password1')
        password2 = self.cleaned_data.get('new_password2')
        if password1 and password2:
            if password1 != password2:
                raise forms.ValidationError(
                    self.error_messages['password_mismatch'],
                    code='password_mismatch',
                )
        return password2

    def save(self, commit=True):
        self.user.set_password(self.cleaned_data['new_password1'])
        if commit:
            self.user.save()
        return self.user

src/hortum/templates/hortum/password_reset.html
<!DOCTYPE html>
<html lang="en">

    <head>
    {% load static %}
    <link rel="icon" type="image/png" href="{% static 'hortum/logo.png' %}"/>
    </head>
    <body BGCOLOR="478C5C">
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Comfortaa:wght@300&display=swap" rel="stylesheet"> 
            <style>
                titulo{
                    color: #FFFF; 
                    font-size:30pt;
                    font-family: Comfortaa;
                }
                h2{
                    color: #FFFF;
                    font-family: Comfortaa;
                }                            
                p{
                    color: #FFFF;
                    font-family: Comfortaa;
                }                
            </style>            
    <center><img src="{% static 'hortum/logo.png' %}" align="BOTTOM" height=100 width=100</center>
    </br>
    <titulo>Hortum</titulo>
    <h2>Redefinir senha<br /></h2>
    <p>Esqueceu sua senha? Insira seu endereço de e-mail abaixo e enviaremos instruções para configurar uma nova senha.</p>
    {% block content %}
        <form method="post">
            {% csrf_token %}
            <p>Email</p>
            {{form.email}}
            <input type="Submit" name="Send email">
        </form>
    {% endblock %}
    </body>
</html>

src/hortum/templates/hortum/password_reset_complete.html
<!DOCTYPE html>
<html lang="en">

    <head>
    {% load static %}
    <link rel="icon" type="image/png" href="{% static 'hortum/logo.png' %}"/>
    </head>
    <body BGCOLOR="478C5C">
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Comfortaa:wght@300&display=swap" rel="stylesheet"> 
            <style>
                titulo{
                    color: #FFFF; 
                    font-size:30pt;
                    font-family: Comfortaa;
                }
                h2{
                    color: #FFFF;
                    font-family: Comfortaa;
                }                            
                p{
                    color: #FFFF;
                    font-family: Comfortaa;
                }                
            </style>            
    <center><img src="{% static 'hortum/logo.png' %}" align="BOTTOM" height=100 width=100</center>
    </br>
    <titulo>Hortum</titulo>
    <h2>Senha redefinida com sucesso!<br /></h2>
    <p>Sua senha foi alterada. Você pode entrar no aplicativo agora.</p>
    </body>
</html>

src/hortum/templates/hortum/password_reset_confirm.html
<!DOCTYPE html>
<html lang="en">

    <head>
    {% load static %}
    <link rel="icon" type="image/png" href="{% static 'hortum/logo.png' %}"/>
    </head>
    <body BGCOLOR="478C5C">
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Comfortaa:wght@300&display=swap" rel="stylesheet"> 
            <style>
                titulo{
                    color: #FFFF; 
                    font-size:30pt;
                    font-family: Comfortaa;
                }
                h2{
                    color: #FFFF;
                    font-family: Comfortaa;
                }                            
                p{
                    color: #FFFF;
                    font-family: Comfortaa;
                }                
            </style>            
    <center><img src="{% static 'hortum/logo.png' %}" align="BOTTOM" height=100 width=100</center>
    </br>
    <titulo>Hortum</titulo>
    <h2>Cadastre sua nova senha<br /></h2>

    {% block content %}

    {% if validlink %}

    <form method="post">{% csrf_token %}
    <fieldset class="module aligned">
        <div class="form-row field-password1">
            {{ form.new_password1.errors }}
            <label for="id_new_password1"><p>Senha:</p></label>
            {{ form.new_password1 }}
        </div>
        <div class="form-row field-password2">
            {{ form.new_password2.errors }}
            <label for="id_new_password2"><p>Confirme a nova senha:</p></label>
            {{ form.new_password2 }}
        </div>
        <br></br>
        <input type="submit" value='Enviar'>
    </fieldset>
    </form>

    {% else %}

    <p>O link de redefinição de senha era inválido, possivelmente porque já foi usado. Solicite uma nova redefinição de senha.</p>

    {% endif %}

    {% endblock %}
    </body>
</html>

src/hortum/templates/hortum/password_reset_done.html
<!DOCTYPE html>
<html lang="en">

    <head>
    {% load static %}
    <link rel="icon" type="image/png" href="{% static 'hortum/logo.png' %}"/>
    </head>
    <body BGCOLOR="478C5C">
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Comfortaa:wght@300&display=swap" rel="stylesheet"> 
            <style>
                titulo{
                    color: #FFFF; 
                    font-size:30pt;
                    font-family: Comfortaa;
                }
                h2{
                    color: #FFFF;
                    font-family: Comfortaa;
                }                            
                p{
                    color: #FFFF;
                    font-family: Comfortaa;
                }                
            </style>            
    <center><img src="{% static 'hortum/logo.png' %}" align="BOTTOM" height=100 width=100</center>
    </br>
    <titulo>Hortum</titulo>
    <h2>Email para redefinir senha enviado<br /></h2>
    <p>Enviamos por e-mail instruções para redefinir sua senha, se houver uma conta com o e-mail que você digitou, você deve recebê-las em breve.</p></br>
    <p>Se você não receber um e-mail, certifique-se de inserir o endereço com o qual se registrou e verifique sua pasta de spam.</p></br>
    </body>
</html>

src/hortum/templates/hortum/user_already_verified_page.html
<!DOCTYPE html>
<html lang="en">

    <head>
    {% load static %}
    <link rel="icon" type="image/png" href="{% static 'hortum/logo.png' %}"/>
        <meta charset="UTF-8">
        <title>Hortum - Conta já ativada!</title>
    </head>
    <body BGCOLOR="478C5C">
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Comfortaa:wght@300&display=swap" rel="stylesheet"> 
            <style>
                titulo{
                    color: #FFFF; 
                    font-size:30pt;
                    font-family: Comfortaa;
                }
                h2{
                    color: #FFFF;
                    font-family: Comfortaa;
                }                
                h1{
                    color: #FFFF;
                    font-family: Comfortaa;
                }                
                p{
                    color: #FFFF;
                    font-family: Comfortaa;
                }                
            </style>            
    <center><img src="{% static 'hortum/logo.png' %}" align="BOTTOM" height=100 width=100</center>
    </br>
    <titulo>Hortum</titulo>
    <h2>Esta conta já foi ativada!<br /></h2>    
    </body>
</html>

 

src/hortum/templates/hortum/user_verify_page.html
<!DOCTYPE html>
<html lang="en">

    <head>
    {% load static %}
    <link rel="icon" type="image/png" href="{% static 'hortum/logo.png' %}"/>
        <meta charset="UTF-8">
        <title>Hortum - Conta ativada</title>
    </head>
    <body BGCOLOR="478C5C">
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Comfortaa:wght@300&display=swap" rel="stylesheet"> 
            <style>
                titulo{
                    color: #FFFF; 
                    font-size:30pt;
                    font-family: Comfortaa;
                }
                h2{
                    color: #FFFF;
                    font-family: Comfortaa;
                }                
                h1{
                    color: #FFFF;
                    font-family: Comfortaa;
                }                
                p{
                    color: #FFFF;
                    font-family: Comfortaa;
                }                
            </style>            
    <center><img src="{% static 'hortum/logo.png' %}" align="BOTTOM" height=100 width=100</center>
    </br>
    <titulo>Hortum</titulo>
    <h2>Conta ativada!<br /></h2>
    <p>Seja bem vindo(a)! Sua conta no aplicativo Hortum foi ativada!</p>
    </body>
</html>

 